In [2]:
import pandas as pd
#check details for file 1
df = pd.read_csv("../../data/gene expression/1_4_hpa_rna_celline.tsv", sep="\t")
print(df.shape)
print(df.columns.tolist())
df.head()

(24315372, 6)
['Gene', 'Gene name', 'Cell line', 'TPM', 'pTPM', 'nTPM']

              Gene Gene name Cell line   TPM  pTPM  nTPM
0  ENSG00000000003    TSPAN6      143B  22.0  27.6  25.9
1  ENSG00000000003    TSPAN6     22Rv1   2.8   3.6   2.7
2  ENSG00000000003    TSPAN6  23132/87   6.2   7.5   7.5
3  ENSG00000000003    TSPAN6      253J  14.2  18.7  25.4
4  ENSG00000000003    TSPAN6   253J-BV  13.0  17.1  18.5

In [4]:
#check details for file 2
df = pd.read_csv("../../data/gene expression/2_DepMap_OmicsExpressionAllGenesTPMLogp1Profile.csv", index_col=0)
print(df.shape)
df.head()

(1495, 53961)

,TSPAN6 (ENSG00000000003),TNMD (ENSG00000000005),DPM1 (ENSG00000000419),SCYL3 (ENSG00000000457),C1orf112 (ENSG00000000460),FGR (ENSG00000000938),CFH (ENSG00000000971),FUCA2 (ENSG00000001036),GCLC (ENSG00000001084),NFYA (ENSG00000001167),...,ENSG00000288714,ENSG00000288717,ENSG00000288718,ENSG00000288719,ENSG00000288720,ENSG00000288721,ENSG00000288722,ENSG00000288723,ENSG00000288724,ENSG00000288725
PR-AdBjpG,4.331992,0.000000,7.364660,2.792855,4.471187,0.028569,1.226509,3.044394,6.500005,4.739848,...,0.000000,0.536053,0.000000,0.028569,0.176323,0.992768,2.797013,0.000000,0.0,0.000000
PR-I2AzwG,4.567424,0.584963,7.106641,2.543496,3.504620,0.000000,0.189034,3.813525,4.221877,3.481557,...,0.000000,0.879706,0.000000,0.014355,0.014355,0.432959,2.972693,0.056584,0.0,0.070389
PR-5ekAAC,3.150560,0.000000,7.379118,2.333424,4.228049,0.056584,1.310340,6.687201,3.682573,3.273516,...,0.028569,0.000000,0.084064,0.000000,0.097611,0.367371,1.695994,0.084064,0.0,0.000000
PR-I21681,5.085340,0.000000,7.154211,2.545968,3.084064,0.000000,5.868390,6.165309,4.489928,3.956986,...,0.000000,0.000000,0.070389,0.000000,0.176323,0.411426,3.921246,0.028569,0.0,0.000000
PR-i9DRP1,6.729417,0.000000,6.537917,2.456806,3.867896,0.799087,7.208478,5.570159,7.127117,4.568032,...,0.000000,0.000000,0.201634,0.028569,0.137504,0.678072,4.418190,0.000000,0.0,0.000000

In [5]:
# peek at the header first without loading the whole thing for file 3
with open("../../data/gene expression/3_GEOexpression.txt") as f:
    first_line = f.readline()
print("First line (first 300 chars):", first_line[:300])

First line (first 300 chars): Gene	GSM101610	GSM101615	GSM101616	GSM101667	GSM101668	GSM101671	GSM101672	GSM101673	GSM101674	GSM101675	GSM101676	GSM101677	GSM101678	GSM101679	GSM101680	GSM101685	GSM101686	GSM101687	GSM101688	GSM1017454	GSM1017455	GSM1017456	GSM1017457	GSM1017458	GSM1017459	GSM1017460	GSM1017461	GSM1017462	GSM101

In [6]:
#check details for file 3
geo = pd.read_csv("../../data/gene expression/3_GEOexpression.txt", sep="\t")
print(geo.shape)
print(geo.columns.tolist()[:10])   # first 10 column names
geo.iloc[:5, :5]

(19914, 3268)
['Gene', 'GSM101610', 'GSM101615', 'GSM101616', 'GSM101667', 'GSM101668', 'GSM101671', 'GSM101672', 'GSM101673', 'GSM101674']

              Gene    GSM101610    GSM101615    GSM101616    GSM101667
0  ENSG00000000003    33.615700   553.249756   540.452209   599.431152
1  ENSG00000000005    40.925682    31.327406    33.934967    34.213123
2  ENSG00000000419  2182.281250  3419.430420  3514.540039  2295.817383
3  ENSG00000000457    58.934814    95.068222    94.900459    51.810070
4  ENSG00000000460   136.418900   257.929169   271.317230   162.090073

In [7]:
#check details for file 4
df = pd.read_csv("../../data/gene expression/4_Harmonized_MS_CCLE_Gygi_subsetted.csv", index_col=0)
print(df.shape)
print(df.columns.tolist()[:5])   # first few column names
df.iloc[:5, :5]

(375, 12558)
['A0AV96 (RBM47)', 'A0AVF1 (IFT56)', 'A0AVG3 (TSNARE1)', 'A0AVI4 (TMEM129)', 'A0AVK6 (E2F8)']

,A0AV96 (RBM47),A0AVF1 (IFT56),A0AVG3 (TSNARE1),A0AVI4 (TMEM129),A0AVK6 (E2F8)
ACH-000849,0.358567,-0.172066,NaN,NaN,NaN
ACH-000441,-1.112410,0.339446,NaN,NaN,NaN
ACH-000248,0.855575,-0.181171,NaN,NaN,NaN
ACH-000684,0.061377,-0.341233,NaN,NaN,NaN
ACH-000856,0.284258,-0.059558,NaN,NaN,NaN

In [8]:
#check details for file 5
df = pd.read_csv("../../data/gene properties/5_OmicsFusionFilteredSupplementary.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(184237, 30)
['Unnamed: 0', 'SequencingID', 'ModelID', 'IsDefaultEntryForModel', 'ModelConditionID', 'IsDefaultEntryForMC', 'CanonicalFusionName', 'gene1(ENS ID)', 'gene2(ENS ID)', 'TotalReadsInSample', 'TotalReadsSupportingFusion', 'FFPM', 'confidence', 'split_reads1', 'split_reads2', 'discordant_mates', 'strand1(gene/fusion)', 'strand2(gene/fusion)', 'reading_frame', 'breakpoint1', 'breakpoint2', 'site1', 'site2', 'type', 'coverage1', 'coverage2', 'tags', 'retained_protein_domains', 'direction1', 'direction2']

,Unnamed: 0,SequencingID,ModelID,IsDefaultEntryForModel,ModelConditionID,IsDefaultEntryForMC,CanonicalFusionName,gene1(ENS ID),gene2(ENS ID),TotalReadsInSample,...,breakpoint2,site1,site2,type,coverage1,coverage2,tags,retained_protein_domains,direction1,direction2
0,0,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,DLG1--SERPINI1,DLG1 (ENSG00000075711.21),SERPINI1 (.),47434547,...,chr3:167836645,CDS/splice-site,intergenic,inversion,1454,76,.,.,upstream,upstream
1,1,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,ADAM17--ITGB1BP1,ADAM17 (ENSG00000151694.14),ITGB1BP1 (ENSG00000119185.13),47434547,...,chr2:9414256,CDS/splice-site,CDS/splice-site,deletion/read-through,883,724,.,.,upstream,downstream
2,2,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,ADAM17--ITGB1BP1,ADAM17 (ENSG00000151694.14),ITGB1BP1 (ENSG00000119185.13),47434547,...,chr2:9412405,CDS/splice-site,CDS/splice-site,deletion/read-through,883,754,.,.,upstream,downstream
3,3,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,ADAM17--ITGB1BP1,ADAM17 (ENSG00000151694.14),ITGB1BP1 (ENSG00000119185.13),47434547,...,chr2:9414256,exon/splice-site,CDS/splice-site,deletion/read-through,41,724,.,.,upstream,downstream
4,4,CDS-010xbm,ACH-001113,Yes,MC-001113-k2lR,Yes,ADAM17--ITGB1BP1,ADAM17 (ENSG00000151694.14),ITGB1BP1 (ENSG00000119185.13),47434547,...,chr2:9408205,CDS/splice-site,CDS/splice-site,deletion/read-through,883,680,.,.,upstream,downstream

In [9]:
#check details for file 6
df = pd.read_csv("../../data/gene properties/6_OmicsSomaticMutationsProfile.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_15588\4206586948.py:2: DtypeWarning: Columns (22,50,54,56,57,58,59,61) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../../data/gene properties/6_OmicsSomaticMutationsProfile.csv")

(1066869, 70)
['Chrom', 'Pos', 'Ref', 'Alt', 'AF', 'DP', 'RefCount', 'AltCount', 'GT', 'PS', 'VariantType', 'VariantInfo', 'DNAChange', 'ProteinChange', 'HugoSymbol', 'Exon', 'Intron', 'EnsemblGeneID', 'EnsemblFeatureID', 'HgncName', 'HgncFamily', 'UniprotID', 'DbsnpRsID', 'GcContent', 'LofGeneName', 'LofGeneId', 'LofNumberOfTranscriptsInGene', 'LofPercentOfTranscriptsAffected', 'NMD', 'MolecularConsequence', 'VepImpact', 'VepBiotype', 'VepHgncID', 'VepExistingVariation', 'VepManeSelect', 'VepENSP', 'VepSwissprot', 'Sift', 'Polyphen', 'GnomadeAF', 'GnomadgAF', 'VepClinSig', 'VepSomatic', 'VepPliGeneValue', 'VepLofTool', 'OncogeneHighImpact', 'TumorSuppressorHighImpact', 'TranscriptLikelyLof', 'Brca1FuncScore', 'CivicID', 'CivicDescription', 'CivicScore', 'LikelyLoF', 'HessDriver', 'HessSignature', 'RevelScore', 'PharmgkbId', 'DidaID', 'DidaName', 'GwasDisease', 'GwasPmID', 'GtexGene', 'ProveanPrediction', 'AMClass', 'AMPathogenicity', 'Rescue', 'RescueReason', 'ProfileID', 'Hotspot', 'EntrezGeneID']

,Chrom,Pos,Ref,Alt,AF,DP,RefCount,AltCount,GT,PS,...,GwasPmID,GtexGene,ProveanPrediction,AMClass,AMPathogenicity,Rescue,RescueReason,ProfileID,Hotspot,EntrezGeneID
0,chr1,818203,G,A,0.240,27,21,6,0/1,NaN,...,NaN,NaN,NaN,NaN,NaN,False,NaN,PR-t8SaQo,False,400728.0
1,chr1,851926,G,A,0.158,17,15,2,0/1,NaN,...,NaN,NaN,NaN,NaN,NaN,False,NaN,PR-lhMBt6,False,643837.0
2,chr1,924510,GC,AA,0.412,35,21,14,0|1,924510.0,...,NaN,NaN,NaN,NaN,NaN,False,NaN,PR-uKiczK,False,148398.0
3,chr1,924657,C,G,0.437,17,9,8,0/1,NaN,...,NaN,NaN,NaN,NaN,NaN,False,NaN,PR-sxFiuq,False,148398.0
4,chr1,924750,C,T,0.625,19,7,12,0/1,NaN,...,NaN,NaN,NaN,NaN,NaN,False,NaN,PR-DNEoiz,False,148398.0

In [10]:
#check details for file 7
df = pd.read_csv("../../data/nomenclature/7_cellosaurus.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(152231, 17)
['Identifier (cell line name)', 'Accession (CVCL_xxxx)', 'Secondary accession number(s)', 'Synonyms', 'Cross-references', 'References identifiers', 'Web pages', 'Comments', 'STR profile data', 'Diseases', 'Species of origin', 'Hierarchy', 'Originate from same individual', 'Sex of cell', 'Age of donor at sampling', 'Category', 'Date (entry history)']

,Identifier (cell line name),Accession (CVCL_xxxx),Secondary accession number(s),Synonyms,Cross-references,References identifiers,Web pages,Comments,STR profile data,Diseases,Species of origin,Hierarchy,Originate from same individual,Sex of cell,Age of donor at sampling,Category,Date (entry history)
0,#132 PC3-1-SC-E8,CVCL_B0T9,NaN,Z48-5MG-70,Wikidata; Q108819335,Patent=EP0501779A1;,NaN,Group: Patented cell line. || Registration: In...,NaN,NaN,NCBI_TaxID=10090; ! Mus musculus (Mouse),CVCL_D145 ! HL-1 Friendly Myeloma-653,NaN,NaN,NaN,Hybridoma,Created: 23-09-21; Last updated: 30-01-24; Ver...
1,#132 PL12 SC-D1,CVCL_B0T8,NaN,Z48-5MG-63,Wikidata; Q108819336,Patent=EP0501779A1;,NaN,Group: Patented cell line. || Registration: In...,NaN,NaN,NCBI_TaxID=10090; ! Mus musculus (Mouse),CVCL_D145 ! HL-1 Friendly Myeloma-653,NaN,NaN,NaN,Hybridoma,Created: 23-09-21; Last updated: 30-01-24; Ver...
2,#15310-LN,CVCL_E548,NaN,15310-LN; TER461; TER-461; Ter 461; TER479; TE...,dbMHC; 48439 || ECACC; 94050311 || IHW; IHW093...,NaN,http://pathology.ucla.edu/workfiles/360cx.pdf ...,Part of: 12th International Histocompatibility...,NaN,NaN,NCBI_TaxID=9606; ! Homo sapiens (Human),NaN,NaN,Female,Age unspecified,Transformed cell line,Created: 22-10-12; Last updated: 30-01-24; Ver...
3,#16-15,CVCL_KA96,NaN,NaN,RCB; RCB4635 || Wikidata; Q54422067,PubMed=25400923;,NaN,Monoclonal antibody isotype: IgM. || Monoclona...,NaN,NaN,NCBI_TaxID=10090; ! Mus musculus (Mouse) || NC...,CVCL_4032 ! P3X63Ag8.653,NaN,NaN,NaN,Hybridoma,Created: 22-08-17; Last updated: 21-03-23; Ver...
4,#40a,CVCL_IW91,NaN,NaN,Wikidata; Q54422071,PubMed=28159921;,NaN,Characteristics: Established from parent cell ...,NaN,NCIt; C21619; Mouse mesothelioma,NCBI_TaxID=10090; ! Mus musculus (Mouse),CVCL_IW90 ! 40,NaN,Male,1-2M,Cancer cell line,Created: 15-05-17; Last updated: 29-06-23; Ver...

In [11]:
#check details for file 8
df = pd.read_csv("../../data/nomenclature/8_DepMap_OmicsProfiles.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(3830, 5)
['ProfileID', 'ModelCondition', 'ModelID', 'Datatype', 'WESKit']

   ProfileID  ModelCondition     ModelID Datatype WESKit
0  PR-00UtU3  MC-001131-kkJv  ACH-001131      wgs    NaN
1  PR-01r7OM  MC-000957-Yckn  ACH-000957      rna    NaN
2  PR-02XmLG  MC-002785-qo9e  ACH-002785      rna    NaN
3  PR-04VvBz  MC-001289-BpdI  ACH-001289      wes    ICE
4  PR-09gmEI  MC-000520-YIm7  ACH-000520      rna    NaN

In [12]:
#check details for file 9
df = pd.read_csv("../../data/nomenclature/9_DepMap_sample_info.csv")
print(df.shape)
print(df.columns.tolist())
df.head()

(1840, 29)
['DepMap_ID', 'cell_line_name', 'stripped_cell_line_name', 'CCLE_Name', 'alias', 'COSMICID', 'sex', 'source', 'RRID', 'WTSI_Master_Cell_ID', 'sample_collection_site', 'primary_or_metastasis', 'primary_disease', 'Subtype', 'age', 'Sanger_Model_ID', 'depmap_public_comments', 'lineage', 'lineage_subtype', 'lineage_sub_subtype', 'lineage_molecular_subtype', 'default_growth_pattern', 'model_manipulation', 'model_manipulation_details', 'patient_id', 'parent_depmap_id', 'Cellosaurus_NCIt_disease', 'Cellosaurus_NCIt_id', 'Cellosaurus_issues']

,DepMap_ID,cell_line_name,stripped_cell_line_name,CCLE_Name,alias,COSMICID,sex,source,RRID,WTSI_Master_Cell_ID,...,lineage_sub_subtype,lineage_molecular_subtype,default_growth_pattern,model_manipulation,model_manipulation_details,patient_id,parent_depmap_id,Cellosaurus_NCIt_disease,Cellosaurus_NCIt_id,Cellosaurus_issues
0,ACH-000016,SLR 21,SLR21,SLR21_KIDNEY,NaN,NaN,NaN,Academic lab,CVCL_V607,NaN,...,NaN,NaN,NaN,NaN,NaN,PT-JnARLB,NaN,Clear cell renal cell carcinoma,C4033,NaN
1,ACH-000032,MHH-CALL-3,MHHCALL3,MHHCALL3_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,NaN,NaN,Female,DSMZ,CVCL_0089,NaN,...,b_cell,NaN,NaN,NaN,NaN,PT-p2KOyI,NaN,Childhood B acute lymphoblastic leukemia,C9140,NaN
2,ACH-000033,NCI-H1819,NCIH1819,NCIH1819_LUNG,NaN,NaN,Female,Academic lab,CVCL_1497,NaN,...,NSCLC_adenocarcinoma,NaN,NaN,NaN,NaN,PT-9p1WQv,NaN,Lung adenocarcinoma,C3512,NaN
3,ACH-000043,Hs 895.T,HS895T,HS895T_FIBROBLAST,NaN,NaN,Female,ATCC,CVCL_0993,NaN,...,NaN,NaN,2D: adherent,NaN,NaN,PT-rTUVZQ,NaN,Melanoma,C3224,NaN
4,ACH-000049,HEK TE,HEKTE,HEKTE_KIDNEY,NaN,NaN,NaN,Academic lab,CVCL_WS59,NaN,...,NaN,NaN,NaN,immortalized,NaN,PT-qWYYgr,NaN,NaN,NaN,No information is available about this cell li...

In [13]:
#check details for file 10
geoinfo = pd.read_csv("../../data/nomenclature/10_GEOInfo.txt", sep="\t")
print(geoinfo.shape)
print(geoinfo.columns.tolist())
geoinfo.head()

(3267, 23)
['Geo_accession', 'CEL_file_names', 'title', 'status', 'submission_date', 'last_update_date', 'type', 'channel_count', 'source_name_ch1', 'organism_ch1', 'characteristics_ch1', 'platform_id', 'contact_country', 'contact_institute', 'GSE_ID', 'GSE_filename', 'cell_line', 'disease', 'origin', 'Cellosaurus_ID', 'Cellline', 'Matching_Type', 'cell_line_Trimmed']

,Geo_accession,CEL_file_names,title,status,submission_date,last_update_date,type,channel_count,source_name_ch1,organism_ch1,...,contact_institute,GSE_ID,GSE_filename,cell_line,disease,origin,Cellosaurus_ID,Cellline,Matching_Type,cell_line_Trimmed
0,GSM101610,GSM101610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CVCL_0131,A-172,Cello GEO GSM,NaN
1,GSM101615,GSM101615,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CVCL_0393,LN-229,Cello GEO GSM,NaN
2,GSM101616,GSM101616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CVCL_0393,LN-229,Cello GEO GSM,NaN
3,GSM101667,GSM101667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CVCL_1715,SW1088,Cello GEO GSM,NaN
4,GSM101668,GSM101668,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,CVCL_1715,SW1088,Cello GEO GSM,NaN

In [14]:
#check details for file 11
df = pd.read_csv("../../data/nomenclature/11_hpa_rna_celline_description.tsv", sep="\t")
print(df.shape)
print(df.columns.tolist())
df.head()

(1206, 7)
['Cell line', 'Disease', 'Disease subtype', 'Cellosaurus ID', 'Patient', 'Primary/Metastasis', 'Sample collection site']

,Cell line,Disease,Disease subtype,Cellosaurus ID,Patient,Primary/Metastasis,Sample collection site
0,143B,Bone cancer,Osteosarcoma,CVCL_2270,13,Primary,bone
1,22Rv1,Prostate cancer,Adenocarcinoma,CVCL_1045,Male,primary,prostate
2,23132/87,Gastric cancer,Adenocarcinoma,CVCL_1046,"Male, 72",primary,stomach
3,253J,Bladder cancer,Carcinoma,CVCL_7935,"Male, 53",metastasis,lymph node
4,253J-BV,Bladder cancer,Carcinoma,CVCL_7937,"Male, 53",metastasis,lymph node

In [15]:
#check details for file 12
metabolomics = pd.read_csv("../../data/non gene expression/12_CCLE_metabolomics_20190502.csv")
# fix the one missing ACH ID
#metabolomics.loc[metabolomics["CCLE_ID"] == "OC315_OVARY", "DepMap_ID"] = "ACH-001144"
print(metabolomics.shape)
metabolomics.head()

(928, 227)

,CCLE_ID,DepMap_ID,2-aminoadipate,3-phosphoglycerate,alpha-glycerophosphate,4-pyridoxate,aconitate,adenine,adipate,alpha-ketoglutarate,...,C56:8 TAG,C56:7 TAG,C56:6 TAG,C56:5 TAG,C56:4 TAG,C56:3 TAG,C56:2 TAG,C58:8 TAG,C58:7 TAG,C58:6 TAG
0,DMS53_LUNG,ACH-000698,6.112727,6.034198,5.896896,6.000532,5.513618,5.868529,5.977177,5.693074,...,6.070239,6.133433,6.091089,6.257711,6.372732,6.202511,5.939576,6.309821,6.115974,5.999436
1,SW1116_LARGE_INTESTINE,ACH-000489,5.577413,5.727045,5.111468,6.073250,5.802494,5.824473,5.888821,5.768379,...,6.248653,6.633575,6.378052,6.341043,6.360945,6.333540,6.137271,7.065858,6.832174,6.363064
2,NCIH1694_LUNG,ACH-000431,5.886398,5.574881,5.541259,5.848375,5.665026,5.875548,5.894904,5.839640,...,5.942887,5.946988,5.837980,5.913350,6.137530,5.807546,5.704149,5.881193,5.785208,5.504225
3,P3HR1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000707,5.770030,6.099229,6.233259,5.543495,5.767759,6.155905,6.111148,5.949481,...,6.516922,6.113791,6.282113,6.248667,6.109480,6.043570,5.846802,6.429402,5.779815,6.241530
4,HUT78_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,ACH-000509,5.480683,5.469742,6.509397,6.251005,5.190578,5.897085,6.148333,5.607481,...,6.161981,6.777932,6.676390,6.695659,6.751029,6.385056,6.682612,6.757899,6.728570,6.879260

In [16]:
#check details for file 13
from cmapPy.pandasGEXpress.parse import parse

mirna_gct = parse("../../data/non gene expression/13_CCLE_miRNA_20181103.gct")
mirna = mirna_gct.data_df.copy()
mirna.index = mirna_gct.row_metadata_df["Description"]   # real miRNA names
mirna.index.name = "miRNA"
print(mirna.shape)
mirna.iloc[:5, :5]
# note: cell-line columns still CCLE names here — harmonise to ACH as a next step

C:\Users\HP\miniconda3\envs\text_analytics\Lib\site-packages\cmapPy\pandasGEXpress\parse_gct.py:251: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  row_metadata = row_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))
C:\Users\HP\miniconda3\envs\text_analytics\Lib\site-packages\cmapPy\pandasGEXpress\parse_gct.py:277: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  col_metadata = col_metadata.apply(lambda x: pd.to_numeric(x, errors="ignore"))

(734, 954)

cid,DMS53_LUNG,SW1116_LARGE_INTESTINE,NCIH1694_LUNG,P3HR1_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE,HUT78_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE
miRNA,,,,,
hsa-let-7a,4362.580078,5191.500000,24991.050781,3253.830078,225.279999
hsa-let-7b,187.440002,868.219971,5066.089844,74.209999,35.740002
hsa-let-7c,267.029999,244.880005,818.489990,53.279999,27.190001
hsa-let-7d,868.109985,556.549988,3661.860107,315.869995,94.000000
hsa-let-7e,1.040000,92.019997,942.619995,1.900000,0.770000

In [17]:
#check details for file 14
signatures = pd.read_csv("../../data/non gene expression/14_OmicsGlobalSignatures.csv")
sig_cols = ["ModelID", "MSIScore", "LoHFraction", "WGD", "CIN", "Ploidy", "Aneuploidy"]
signatures_clean = signatures[signatures["IsDefaultEntryForModel"] == "Yes"][sig_cols].copy()
signatures_clean = signatures_clean.set_index("ModelID")
print(signatures_clean.shape)
signatures_clean.head()

(1955, 6)

            MSIScore  LoHFraction  WGD       CIN    Ploidy  Aneuploidy
ModelID
ACH-000839      3.68     0.107443  1.0  0.502634  3.158291        20.0
ACH-000041      2.21     0.130089  1.0  0.523865  3.236089        19.0
ACH-002046      2.87     0.222342  1.0  0.679772  3.326715        30.0
ACH-002048      2.48          NaN  NaN       NaN       NaN         NaN
ACH-000042      2.07          NaN  NaN       NaN       NaN         NaN